import "./globals.css";
import Footer from "@/components/footer";
import SessionWrapper from "./components/SessionWrapper.js";

export const metadata = {
  title: "coffee for code",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body>
            {children}
            <Footer/>
        </body>
      </SessionWrapper>
    </html>
  );
}
